# Generated by Django 3.2.8 on 2021-11-16 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0002_auto_20211116_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebrities',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stars.category'),
        ),
        migrations.AlterField(
            model_name='celebrities',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
