# Generated by Django 3.2.8 on 2021-11-16 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0003_auto_20211116_0648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celebrities',
            name='cat',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
